[project]
name = "test-pypi-continu-inzicht-main"
version = "0.1.0"
description = "Test package to "
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
 "pytest>=9.0.2",
 "python-dotenv",
 "toml",
]
