name: Run Pytest with UV and Nox

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out TBCI repository
        uses: actions/checkout@v4 
        with:
          # this still needs adjusting if we want this on a PR 
          # we can also run this locally manuall & check on github later once in main
          repository: continu-inzicht/toolbox-continu-inzicht 
          path: toolbox-continu-inzicht
          lfs: true

      - name: Check own repository
        uses: actions/checkout@v4
        with:
          repository: continu-inzicht/test-package-installation
          path: test-package-installation 
      
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.3"
      
      - name: debug
        run: | 
            ls ${{ github.workspace }}\test-package-installation 
            ls ${{ github.workspace }}\toolbox-continu-inzicht"
            ls ${{ github.workspace }}\toolbox-continu-inzicht//src"
        shell: pwsh
      - name: Copy github secrets to environment variables files
        # remove get content if add secrets later
        run: |
            Add-Content -Path .env -Value "TBCI_MAIN_REPO_PATH=${{ github.workspace }}\toolbox-continu-inzicht"
            Get-Content .env
        shell: pwsh
      - name: Install the project
        run: uv sync --locked

      - name: Run Pytests
        run: uv run run_tests_uv.py log=false # in terminal rather than log file

      - name: Upload Benchmark Data
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-data
          path: .benchmarks/
